name: Package

on:
  release:
    types:
      - created

jobs:
  package:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Package
        run: npm run package
