name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Test Job
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci

      - name: Run - Test
        run: xvfb-run -a npm run test


  # Build Job
  build:
    needs: [test]
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci

      - name: Run - Lint
        run: npm run lint

      - name: Run - Build
        run: npm run compile

      - name: Create Package for Release
        run: npx semantic-release --extends ./package.release.config.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - uses: actions/upload-artifact@v4
        with:
          name: Upload VSIX Artifact
          path: "*.vsix"


  # Release Job
  release:
    needs: [test, build]
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci

      - name: Download VSIX Artifact
        uses: actions/download-artifact@v4
        with:
          pattern: "*.vsix"

      - if: github.event_name == 'push' || github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        name: Create Release
        run: npx semantic-release --extends ./publish.release.config.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
