name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      
      - uses: actions/checkout@v4
      
      # Install Node.js and Npm dependencies
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Npm Install
        run: npm install

      # Run Build commands
      - name: Run - Lint
        run: npm run lint
      - name: Run - Build
        run: npm run compile
      - name: Run - Test
        run: xvfb-run -a npm run test

      # Conditionally publish the package automatically if release created
      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
